[versions]
agp = "8.2.0"
kotlin = "1.9.20"
compose = "1.5.10"
wire = "4.9.3"

[libraries]
wire-runtime = { module = "com.squareup.wire:wire-runtime", version.ref = "wire" }
wire-grpc = { module = "com.squareup.wire:wire-grpc-client", version.ref = "wire" }

[plugins]
androidApplication = { id = "com.android.application", version.ref = "agp" }
androidLibrary = { id = "com.android.library", version.ref = "agp" }
kotlinMultiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
jetbrainsCompose = { id = "org.jetbrains.compose", version.ref = "compose" }
